import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import Slider from '../components/slider'
import { prisma } from '../lib/db'
import News from '../components/news'

const Home: NextPage = () => {
  return (
    <div className='bg-gray-900 container mx-10'>
      <Head>
        <title>Tech Advisor</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Nav/> */}
      <Slider />
      <News />
    </div>
  )
}

export default Home

// export const getStaticProps: GetStaticProps = async () => {
//   const brands = await prisma.brand.findMany({ select: { name: true, phonesNum: true } })
//   console.log(brands);

//   return { props: { brands } }
// }
